hided_command:
  - ?
  - about
  - advancement
  - ajl
  - ajlb
  - ajleaderboards
  - alb
  - animatedsb
  - animatedscoreboard
  - as
  - asb
  - ban
  - ban-ip
  - banlist
  - blockdata
  - blockmsg
  - chatrelaod
  - cleanmotd
  - clear
  - clone
  - clt
  - clx
  - combat-timer
  - combatlog
  - combatlogx
  - combattag
  - combattagx
  - combattime
  - combattimer
  - ct
  - ctime
  - ctx
  - debug
  - debug-event
  - debugevent
  - decentholograms
  - defaultgamemode
  - deop
  - difficulty
  - effect
  - enchant
  - entitydata
  - execute
  - fill
  - filter
  - function
  - gamemode
  - gamerule
  - give
  - global-gamerule
  - globalgamerule
  - help
  - icanhasbukkit
  - item-info
  - item-information
  - item-to-b64
  - item-to-base64
  - item-to-json
  - item-to-nbt
  - item-to-yml
  - iteminfo
  - iteminformation
  - itemtob64
  - itemtobase64
  - itemtojson
  - itemtonbt
  - itemtoyml
  - kick
  - list
  - locate
  - lp
  - luckperms
  - me
  - nametagedit
  - ne
  - nte
  - op
  - packet
  - packet_filter
  - packetlog
  - paper
  - papi
  - pardon
  - pardon-ip
  - particle
  - perm
  - permission
  - permissions
  - perms
  - pl
  - placeholderapi
  - playsound
  - plugins
  - protocol
  - pvp
  - pvvtoggle
  - recipe
  - reload
  - replaceitem
  - restart
  - rl
  - save-all
  - save-off
  - save-on
  - say
  - sb
  - sbapi
  - sbc
  - sbcore
  - scoreboard
  - seed
  - setblock
  - setidletimeout
  - setworldspawn
  - sirblobman
  - sirblobmanapi
  - sirblobmancore
  - spawnpoint
  - spigot
  - spreadplayers
  - stats
  - stop
  - stopsound
  - summon
  - tablist
  - tellraw
  - testfor
  - testforblock
  - testforblocks
  - timings
  - title
  - tl
  - toggledownfall
  - togglepvp
  - trigger
  - vault-convert
  - vault-info
  - ver
  - version
  - viaver
  - viaversion
  - vvbukkit
  - weather
  - whitelist
  - worldborder
  - xp
  - znpcs
disabled_command:
  - about
  - advancement
  - ajl
  - ajlb
  - ajleaderboards
  - alb
  - animatedsb
  - animatedscoreboard
  - as
  - asb
  - ban
  - ban-ip
  - banlist
  - blockdata
  - blockmsg
  - chatrelaod
  - cleanmotd
  - clear
  - clone
  - clt
  - clx
  - combat-timer
  - combatlog
  - combatlogx
  - combattag
  - combattagx
  - combattime
  - combattimer
  - ct
  - ctime
  - ctx
  - debug
  - debug-event
  - debugevent
  - decentholograms
  - defaultgamemode
  - deop
  - difficulty
  - effect
  - enchant
  - entitydata
  - execute
  - fill
  - filter
  - function
  - gamemode
  - gamerule
  - give
  - global-gamerule
  - globalgamerule
  - icanhasbukkit
  - item-info
  - item-information
  - item-to-b64
  - item-to-base64
  - item-to-json
  - item-to-nbt
  - item-to-yml
  - iteminfo
  - iteminformation
  - itemtob64
  - itemtobase64
  - itemtojson
  - itemtonbt
  - itemtoyml
  - kick
  - list
  - locate
  - me
  - nametagedit
  - ne
  - nte
  - op
  - packet
  - packet_filter
  - packetlog
  - paper
  - pardon
  - pardon-ip
  - particle
  - perm
  - permission
  - permissions
  - perms
  - pl
  - playsound
  - plugins
  - pvp
  - pvvtoggle
  - recipe
  - reload
  - replaceitem
  - restart
  - rl
  - save-all
  - save-off
  - save-on
  - say
  - sb
  - sbapi
  - sbc
  - sbcore
  - scoreboard
  - seed
  - setblock
  - setidletimeout
  - setworldspawn
  - sirblobman
  - sirblobmanapi
  - sirblobmancore
  - spawnpoint
  - spigot
  - spreadplayers
  - stats
  - stop
  - stopsound
  - summon
  - tablist
  - tellraw
  - testfor
  - testforblock
  - testforblocks
  - timings
  - title
  - tl
  - toggledownfall
  - togglepvp
  - trigger
  - vault-convert
  - vault-info
  - ver
  - version
  - viaver
  - viaversion
  - vvbukkit
  - weather
  - whitelist
  - worldborder
  - xp
  - znpcs